# Generated by Django 2.2 on 2021-07-29 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_schoolname_streem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolname',
            name='streem_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.StudentStreem'),
        ),
    ]
